version: '3'

services:
  grafana:
    image: grafana/grafana
    ports:
      - '3014:3000'
    environment:
      - 'GF_SECURITY_ADMIN_PASSWORD=yourpassword'
    volumes:
      - grafana_data:/opt/grafana/data
volumes:
  grafana_data:
    driver: local