version: "3.3"

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  nginx:
    container_name: nginx
    restart: always
    tty: true
    image: nginx
    user: root
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80

  grafana:
    # ports:
    #   - "3000:3000"
    user: root
    container_name: grafana
    volumes:
      - "grafana_data:/var/lib/grafana"
      - "./grafana/provisioning/datasources/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml"
    image: grafana/grafana:10.0.1
    # environment:
    #   - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    #   - GF_AUTH_ANONYMOUS_ENABLED=true
    #   - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
  prometheus:
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - prometheus_data:/prometheus
    image: prom/prometheus:v2.45.0

  loki:
    image: grafana/loki:2.8.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
