# docker-compose.yaml
version: '3.8'
services:
  jenkins:
    container_name: jenkins
    restart: unless-stopped
    build: .
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
  proxy:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
    depends_on:
      - jenkins
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
volumes:
  jenkins:
