version: '3.7'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=mongodb
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=changeme
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
      
volumes:
  mongo-data:

